### ISSUE TITLE
Terraform import of sleuth_code_change_source does not pull in repository information

### ISSUE THREAD

**Issue by Warsinger** [sleuth-io/terraform-provider-sleuth#133]
### Terraform Version
Terraform v1.5.6
on darwin_arm64
+ provider registry.terraform.io/sleuth-io/sleuth v0.4.3

### Affected Resource(s)
Please list the resources as a list, for example:
- sleuth_code_change_source

### Terraform Configuration Files
```
resource "sleuth_code_change_source" "webapp_webapp" {
  #
}
```

### Expected Behavior
Running `terraform import sleuth_code_change_source.webapp_webapp webapp/webapp` should provide the state file filled out with the proper information.

### Actual Behavior
The repository was generated as a blank array in the JSON of the .tfstate file after the import as seen in the output below
```
   {
      "mode": "managed",
      "type": "sleuth_code_change_source",
      "name": "webapp_webapp",
      "provider": "provider[\"registry.terraform.io/sleuth-io/sleuth\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "auto_tracking_delay": 0,
            "build_mappings": [],
            "collect_impact": true,
            "deploy_tracking_type": "manual",
            "environment_mappings": [
              {
                "branch": "main",
                "environment_slug": "development-2",
                "id": "webapp/development-2"
              },
              {
                "branch": "main",
                "environment_slug": "production",
                "id": "webapp/production"
              },
              {
                "branch": "main",
                "environment_slug": "development",
                "id": "webapp/development"
              }
            ],
            "id": "webapp/webapp",
            "include_in_dashboard": true,
            "name": "Webapp",
            "notify_in_slack": true,
            "path_prefix": "",
            "project_slug": "webapp",
            "repository": []
          },
          "sensitive_attributes": [],
        }
      ]
    },
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import sleuth_code_change_source.webapp_webapp webapp/webapp`

**Comment by JureMalovrh** [comment]
Hi, could you run the code with `TF_LOG_PROVIDER=debug` being set to see if the setting of a repository in state fails.
