### ISSUE TITLE
Unable to destroy environment resources with single environment projects

### ISSUE THREAD

**Issue by lunnydan** [sleuth-io/terraform-provider-sleuth#136]
### Terraform Version

Terraform v1.5.3
on darwin_arm64

Provider registry.terraform.io/sleuth-io/sleuth v0.4.3

### Affected Resource(s)

sleuth_environment
sleuth_project

### Terraform Configuration Files
```hcl
resource "sleuth_project" "project" {
  name           = "some_repo_project"
  build_provider = "GITHUB"
}

resource "sleuth_environment" "environments" {
  project_slug = "${sleuth_project.project.slug}"
  name         = "Production"
  color        = "#2F7604"
}
```

### Debug Output
[Debug output](https://gist.github.com/lunnydan/f874c9a4c325abacf6572546006f062c)

### Expected Behavior
Running `terraform destroy --auto-approve` should destroy the environment and project in sleuth and remove them from the state file.

### Actual Behavior
The destroy errors out with the error `Error: Missing` when trying to destroy the environment resource. This blocks the project from being destroyed due to the dependancy tree. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply --auto-approve`
2. `terraform destroy --auto-approve`

**Comment by JureMalovrh** [comment]
Hi, thanks for the issue. We are aware of the problem, but the issue is with our API and the way Terraform executes dependent resources which is not in sync.

For a workaround, you can manually remove the default environment out of the terraform state, and then the destroy should work.
