### ISSUE TITLE
Cross compile for Darwin ARM64

### ISSUE THREAD

**Issue by jjm** [sleuth-io/terraform-provider-sleuth#23]
Now the Apple M1 Mac's are quite common and this provider won't install via `terraform init` due to the missing binary.

**Comment by jjm** [comment]
Looking the `.goreleaser.yml`, this should have been released for arm64 on darwin. However looks like binaries were never uploaded looking at the releases.

https://github.com/sleuth-io/terraform-provider-sleuth/blob/8b1337eb5660d770057545399f266696bba608b1/.goreleaser.yml#L18-L27

**Comment by mrdon** [comment]
Done!
